name=input("Enter your name: ")
age=int(input("Enter your age: "))
height=float(input("Enter your height in metres : "))
favourite_number=int(input("Enter your favourite number: "))
user_height=int(height*100)

print("\n")
print("===============================================")
print("              YOUR PROFILE CARD")
print("===============================================")
print(f"Name:             {name}")
print(f"Age:              {age} years")
print(f"Height:           {height}m ({user_height})cm")
print(f"Favourite number: {favourite_number}")
print("===============================================")
